from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
import google.generativeai as genai

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# PASTE YOUR GEMINI API KEY HERE
genai.configure(api_key="AIzaSyAJLW5FNfkVLHwPwvUfF356-cf6Qfw9xVY")

model = genai.GenerativeModel("gemini-2.0-flash")

@app.get("/")
def home():
    return {
        "message": "Backend Running"
    }

@app.post("/analyze-crop")
async def analyze_crop(file: UploadFile = File(...)):

    prompt = """
    You are an agriculture expert.

    Analyze the crop disease from uploaded crop image.

    Return:
    - disease name
    - confidence percentage
    - symptoms
    - treatment
    - prevention
    - Telugu advice

    Give response in simple JSON style.
    """

    image_bytes = await file.read()

    response = model.generate_content(
        [
            prompt,
            {
                "mime_type": file.content_type,
                "data": image_bytes
            }
        ]
    )

    return {
        "result": response.text,
        "confidence": "AI Generated",
        "symptoms": [
            "AI analyzed symptoms"
        ],
        "treatment": "Generated by Gemini AI",
        "prevention": "Generated by Gemini AI",
        "telugu": "AI ద్వారా వ్యవసాయ సూచనలు"
    }